new commit
Maximumstart-initial-course/polina-b7-001 pull request #3
Opened 2019-04-11 15:44 UTC by Polinaaaaaaa

?

2019-04-17 11:27 UTC, sawex commented
**По поводу ответов на вопросы:**
3. Корректнее будет сказать, что SEO - это комплекс мер, что направлены на бла-бла-бла, а не просто ключевые слова.
6. У тебя максимально правильный ответ. Но рекомендую прочитать еще коротенькую статейку по этому вопросу. Если конкретнее, то ту часть где говорится [про машину Тьюринга](https://habr.com/ru/post/231897/)
7. Ответ верный, но не полный. Забыла про скринридер, который зачитает то, что написано в альте.

**По структуре заполнения answers.html:**
Нужно заполнить его правильно, как указано в примере. Если точнее: 
```
<div class="faq">
    <div class="pair first-lesson">
        <p class="question">Вопрос</p>
        <p class="answer">Ответ</p>
    </div>
    <div class="pair first-lesson">
        <p class="question">Вопрос</p>
        <p class="answer">Ответ</p>
    </div>
</div>
```
Каждый вопрос с ответом в новом блочке. Все они лежать в блоке с классом "faq". Имена классов мы не меняем и не добавляем новых.

**По самостоялочке с котами:**
Все круто, только нужно поменять пути у ссылок потому, что такой путь у меня не отображается: href="file:///C:/Users/Polina/Desktop/polina-b7-001/homeworks/first-lesson/about.html"


На этом все :)
Исправляйте, комитте, пуште :)

2019-04-19 14:19 UTC, Knyazevich commented on homeworks/first-lesson/index.html
> +	<a href="file:///C:/Users/Polina/Desktop/polina-b7-001/homeworks/first-lesson/about.html">Обо мне</a>
Зроби тут відносний шлях.

2019-04-19 14:22 UTC, Knyazevich requested changes

2019-04-19 14:22 UTC, Knyazevich commented on homeworks/first-lesson/index.html
> +src="../../personal/images/1518761974792987039.jpg"></a>
Мені не прилітає нічого з папки __personal__, в тому і перше правило папки __personal__.

2019-04-20 17:20 UTC, Knyazevich approved these changes

2019-04-20 17:33 UTC, merged